(********************************************************************
	@name Coq declarations for model
	@date 2018/08/17 11:47:36
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
 Require Import List.
 Require Import String.
 Require Import core.Model.
 Require Import TTMetamodel.
 
 
 Definition InputModel : Model TruthTableMetamodel_EObject TruthTableMetamodel_ELink :=
 (* TODO*)
 .
 